version: '3'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 1
      interval: 30s
      timeout: 3s
      retries: 3

  mongodb:
    image: mongo:latest
    platform: linux/amd64
